name: cogo_cli_flutter
description: Dart CLI for COGO (migration support for CreateGo CLI)
version: 0.2.6
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.7.0
  http: ^1.2.2
  uuid: ^4.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.7


