name: flutter_chat_app
description: A Flutter chat application using Cogo SDK and CLI
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Cogo packages
  cogo_chat_sdk_flutter:
    path: ../packages/cogo-chat-sdk-flutter
  cogo_cli_flutter:
    path: ../packages/cogo-cli-flutter
  
  # UI dependencies
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  
  # State management
  provider: ^6.1.1
  
  # UI components
  flutter_markdown: ^0.6.18+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
