name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --silent
      - run: npm run -ws --if-present build
      - name: Upload Figma plugin dist
        uses: actions/upload-artifact@v4
        with:
          name: figma-plugin-dist
          path: packages/figma-plugin/dist
