name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --silent
      - run: npm run -w packages/figma-plugin -s pack
      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: packages/figma-plugin/releases/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


